spring:
  config:
    import: optional:file:${CONFIG_PATH:./config/config.yaml}
  application:
    name: door-codes-manager
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: jdbc:sqlite:${DB_PATH:./data/door_codes_manager.db}
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 1
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
vaadin:
  launch-browser: true
server:
  port: 8080